### ISSUE TITLE
Remote Notifications have wrong types on Android

### ISSUE THREAD

**Issue by ryanwilliams** [zo0r/react-native-push-notification#391]
Perhaps I'm using it wrong, but it looks like all remote notification values are `String`, which means this simple notification `{ message: "Foo", vibrate: true }` causes a java exception:

    03-21 13:55:10.846  30869-30869/com.foo V/RNPushNotification﹕ sendNotification: Bundle[{google.sent_time=1490057706016, userInteraction=false, id=-2037751743, vibrate=true, google.message_id=0:1490057706022984%3c5625daf9fd7ecd, message=Foo, foreground=false}]
    03-21 13:55:10.870  30869-30869/com.foo W/Bundle﹕ Key vibrate expected Boolean but value was a java.lang.String.  The default value false was returned.
    03-21 13:55:10.894  30869-30869/com.foo W/Bundle﹕ Attempt to cast generated internal exception:
        java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Boolean
                at android.os.BaseBundle.getBoolean(BaseBundle.java:737)
                at android.os.BaseBundle.getBoolean(BaseBundle.java:697)
                at com.dieam.reactnativepushnotification.modules.RNPushNotificationHelper.sendToNotificationCentre(RNPushNotificationHelper.java:278)
                at com.dieam.reactnativepushnotification.modules.RNPushNotificationListenerService.handleRemotePushNotification(RNPushNotificationListenerService.java:115)
                at com.dieam.reactnativepushnotification.modules.RNPushNotificationListenerService.access$000(RNPushNotificationListenerService.java:25)
                at com.dieam.reactnativepushnotification.modules.RNPushNotificationListenerService$1.run(RNPushNotificationListenerService.java:65)
                at android.os.Handler.handleCallback(Handler.java:751)
                at android.os.Handler.dispatchMessage(Handler.java:95)
                at android.os.Looper.loop(Looper.java:154)
                at android.app.ActivityThread.main(ActivityThread.java:6119)
                at java.lang.reflect.Method.invoke(Native Method)
                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by akrumel** [comment]
I am seeing the same problem. For context, I am using SNS to generate the notification. Digging into the code, all of the values in the Bundle instance passed into RNPushNotificationListenerService.onMessageReceived() are of type String. Calling any of the get*() methods besides getString() will cause a stack trace to be printed and the underlying default value being returned. Note, the exception is caught and logged and then returns a default value to enable normal execution.

I fixed this by changing the code of RNPushNotificationHelper.sendToNotificationCentrer() to check the type of `playSound`, `vibrate`, and `vibration` when set and do the appropriate conversion if the value is a string. For example:

```
if (this.getBundleBoolean(bundle, "playSound")) {...}
```java
where getBundleBoolean() is defined as a private method:

```java
private boolean getBundleBoolean(Bundle bundle, String key) {
    if (!bundle.containsKey(key)) { return false; }

    Object value = bundle.get(key);

    return value instanceof Boolean ?(boolean)value :Boolean.parseBoolean((String)value);
}
```

**Comment by cailenmusselman** [comment]
Just spent the better part of a morning trying to figure out why these boolean parameters weren't working as well.

Is there any plan to have this merged in? 1 year later and the bug still exists in master.
